version: "3"
vars:
  CURRENT_BRANCH:
    sh: "git rev-parse --abbrev-ref HEAD"
  SITE:
    sh: "pwd | xargs basename | sed -re s/-jekyll-theme//"
  DOMAIN:
    sh: "pwd | xargs basename | sed -re s/-jekyll-theme/.sutty.local/"
tasks:
  default:
    deps:
    - "build"
  rubocop:
    desc: "Chequea el código Ruby"
    deps:
    - "bundle"
    cmds:
    - "haini.sh bundle exec rubocop -A"
  url:
    silent: true
    cmds:
    - "echo https://{{.DOMAIN}}:4000/"
  pack:
    desc: "Compila JavaScript"
    deps:
    - "pnpm"
    cmds:
    - "git rm -f assets/js/pack.* || true"
    - "haini.sh ./node_modules/.bin/esbuild _packs/entry.js --analyze --bundle --minify --sourcemap --outdir=assets/js/ --entry-names=\"pack.[hash]\" --metafile=_data/manifest.json"
    - "git add _data/manifest.json assets/js/pack.*"
    - "git commit -m \"[skip ci] JS\""
    - task: "notify"
    sources:
    - "_packs/**/*.js"
    generates:
    - "_data/manifest.json"
  watch:
    desc: "Desarrollar JavaScript"
    deps:
    - "pnpm"
    cmds:
    - "haini.sh ./node_modules/.bin/esbuild _packs/entry.js --analyze --bundle --outfile=pack.js --serve=65001"
  build:
    desc: "Genera el sitio en entorno de desarrollo"
    deps:
    - "url"
    - "pnpm"
    - "bundle"
    - "serve"
    cmds:
    - "haini.sh bundle exec jekyll build --trace --profile"
    - task: "notify"
  bundle:
    desc: "Instala dependencias de Jekyll"
    cmds:
    - "haini.sh bundle"
    sources:
    - "*.gemspec"
    - "Gemfile"
    generates:
    - "Gemfile.lock"
  pnpm:
    desc: "Instala dependencias de JS y CSS"
    cmds:
    - "haini.sh npm install -g pnpm"
    - "haini.sh pnpm install"
    sources:
    - "package.json"
    generates:
    - "pnpm-lock.yaml"
  hosts:
    desc: "Agrega el dominio local a /etc/hosts"
    interactive: true
    cmds:
    - "echo -e \"127.0.0.1 {{.DOMAIN}}\n::1 {{.DOMAIN}}\" | sudo tee -a /etc/hosts"
    status:
    - "grep -q \" {{.DOMAIN}}$\" /etc/hosts"
  serve:
    desc: "Inicia el servidor web de desarrollo"
    deps:
    - "hosts"
    cmds:
    - "haini.sh nginx"
    status:
    - "pgrep -F ../hain/run/nginx/nginx.pid"
  notify: "echo -e \"\a\""
  google-font:
    desc: "Descarga una tipografía desde Google Fonts"
    cmds:
    - "./_bin/download_google_font {{.CLI_ARGS}}"
